version: 2
jobs:
  build:
    docker:
      - image: debian:jessie
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install git
      - run:
          name: Get things
          command: |
            apt-get install autoconf automake libtool curl make g++ unzip
            apt-get install build-essential pkg-config
      - run:
          name: protobuf
          command: |
            curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
            tar -xzf protobuf-cpp-3.6.1.tar.gz
            cd protobuf-3.6.1
            ./configure
            make
            make check
            make install
            ldconfig # refresh shared library cache.
      - run:
          name: grpc
          command: |
            git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
            cd grpc
            git submodule update --init
            make
            make install
      # - run:
      #     name: get clang
      #     command: |
      #       apt-get clang-6.0 lldb-6.0 lld-6.0
      