version: 2
jobs:
  build:
    docker:
      - image: debian:jessie
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Install reqs
          command: |
            apt-get update
            apt-get install curl unzip
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build image
          command: |
            cd .circleci/docker
            docker build -t wbtest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push wbtest
      