# VERS: 0.0.1
FROM debian:8

RUN apt-get update && apt-get install -y \
    ssh \
    ca-certificates \
    git \
    autoconf \
    automake \
    libtool \
    curl \
    make \
    g++ \
    unzip \
    build-essential \
    pkg-config
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz \
    && tar -xzf protobuf-cpp-3.6.1.tar.gz --no-same-owner \
    && cd protobuf-3.6.1 \
    && ./configure \
    && make \
    && make check \
    && make install \
    && ldconfig \
    && git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc \
    && cd grpc \
    && git submodule update --init \
    && make \
    && make install 