FROM debian:8

RUN apt-get update \
    apt-get install git -y \
    apt-get install autoconf automake libtool curl make g++ unzip -y \
    apt-get install build-essential pkg-config -y \
    curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz \
    tar -xzf protobuf-cpp-3.6.1.tar.gz --no-same-owner \
    cd protobuf-3.6.1 \
    ./configure \
    make \
    make check \
    make install \
    ldconfig \
    git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc \
    cd grpc \
    git submodule update --init \
    make \
    make install 