// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Basic.proto

#ifndef PROTOBUF_INCLUDED_Basic_2eproto
#define PROTOBUF_INCLUDED_Basic_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Basic_2eproto 

namespace protobuf_Basic_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Basic_2eproto
namespace api {
class Grid;
class GridDefaultTypeInternal;
extern GridDefaultTypeInternal _Grid_default_instance_;
class GridVertex;
class GridVertexDefaultTypeInternal;
extern GridVertexDefaultTypeInternal _GridVertex_default_instance_;
class SimulationInfo;
class SimulationInfoDefaultTypeInternal;
extern SimulationInfoDefaultTypeInternal _SimulationInfo_default_instance_;
}  // namespace api
namespace google {
namespace protobuf {
template<> ::api::Grid* Arena::CreateMaybeMessage<::api::Grid>(Arena*);
template<> ::api::GridVertex* Arena::CreateMaybeMessage<::api::GridVertex>(Arena*);
template<> ::api::SimulationInfo* Arena::CreateMaybeMessage<::api::SimulationInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace api {

// ===================================================================

class GridVertex : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:api.GridVertex) */ {
 public:
  GridVertex();
  virtual ~GridVertex();

  GridVertex(const GridVertex& from);

  inline GridVertex& operator=(const GridVertex& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GridVertex(GridVertex&& from) noexcept
    : GridVertex() {
    *this = ::std::move(from);
  }

  inline GridVertex& operator=(GridVertex&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GridVertex& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GridVertex* internal_default_instance() {
    return reinterpret_cast<const GridVertex*>(
               &_GridVertex_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GridVertex* other);
  friend void swap(GridVertex& a, GridVertex& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GridVertex* New() const final {
    return CreateMaybeMessage<GridVertex>(NULL);
  }

  GridVertex* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GridVertex>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GridVertex& from);
  void MergeFrom(const GridVertex& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GridVertex* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 neighbors = 5;
  int neighbors_size() const;
  void clear_neighbors();
  static const int kNeighborsFieldNumber = 5;
  ::google::protobuf::uint32 neighbors(int index) const;
  void set_neighbors(int index, ::google::protobuf::uint32 value);
  void add_neighbors(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      neighbors() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_neighbors();

  // uint32 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // float xCoord = 2;
  void clear_xcoord();
  static const int kXCoordFieldNumber = 2;
  float xcoord() const;
  void set_xcoord(float value);

  // float yCoord = 3;
  void clear_ycoord();
  static const int kYCoordFieldNumber = 3;
  float ycoord() const;
  void set_ycoord(float value);

  // float zCoord = 4;
  void clear_zcoord();
  static const int kZCoordFieldNumber = 4;
  float zcoord() const;
  void set_zcoord(float value);

  // @@protoc_insertion_point(class_scope:api.GridVertex)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > neighbors_;
  mutable int _neighbors_cached_byte_size_;
  ::google::protobuf::uint32 index_;
  float xcoord_;
  float ycoord_;
  float zcoord_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Basic_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Grid : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:api.Grid) */ {
 public:
  Grid();
  virtual ~Grid();

  Grid(const Grid& from);

  inline Grid& operator=(const Grid& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Grid(Grid&& from) noexcept
    : Grid() {
    *this = ::std::move(from);
  }

  inline Grid& operator=(Grid&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Grid& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Grid* internal_default_instance() {
    return reinterpret_cast<const Grid*>(
               &_Grid_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Grid* other);
  friend void swap(Grid& a, Grid& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Grid* New() const final {
    return CreateMaybeMessage<Grid>(NULL);
  }

  Grid* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Grid>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Grid& from);
  void MergeFrom(const Grid& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Grid* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .api.GridVertex vertices = 3;
  int vertices_size() const;
  void clear_vertices();
  static const int kVerticesFieldNumber = 3;
  ::api::GridVertex* mutable_vertices(int index);
  ::google::protobuf::RepeatedPtrField< ::api::GridVertex >*
      mutable_vertices();
  const ::api::GridVertex& vertices(int index) const;
  ::api::GridVertex* add_vertices();
  const ::google::protobuf::RepeatedPtrField< ::api::GridVertex >&
      vertices() const;

  // uint32 totalVerts = 1;
  void clear_totalverts();
  static const int kTotalVertsFieldNumber = 1;
  ::google::protobuf::uint32 totalverts() const;
  void set_totalverts(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:api.Grid)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::api::GridVertex > vertices_;
  ::google::protobuf::uint32 totalverts_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Basic_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimulationInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:api.SimulationInfo) */ {
 public:
  SimulationInfo();
  virtual ~SimulationInfo();

  SimulationInfo(const SimulationInfo& from);

  inline SimulationInfo& operator=(const SimulationInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimulationInfo(SimulationInfo&& from) noexcept
    : SimulationInfo() {
    *this = ::std::move(from);
  }

  inline SimulationInfo& operator=(SimulationInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimulationInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimulationInfo* internal_default_instance() {
    return reinterpret_cast<const SimulationInfo*>(
               &_SimulationInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SimulationInfo* other);
  friend void swap(SimulationInfo& a, SimulationInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimulationInfo* New() const final {
    return CreateMaybeMessage<SimulationInfo>(NULL);
  }

  SimulationInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimulationInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SimulationInfo& from);
  void MergeFrom(const SimulationInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimulationInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float elevations = 2;
  int elevations_size() const;
  void clear_elevations();
  static const int kElevationsFieldNumber = 2;
  float elevations(int index) const;
  void set_elevations(int index, float value);
  void add_elevations(float value);
  const ::google::protobuf::RepeatedField< float >&
      elevations() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_elevations();

  // repeated float sediment = 4;
  int sediment_size() const;
  void clear_sediment();
  static const int kSedimentFieldNumber = 4;
  float sediment(int index) const;
  void set_sediment(int index, float value);
  void add_sediment(float value);
  const ::google::protobuf::RepeatedField< float >&
      sediment() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_sediment();

  // repeated int32 plates = 5;
  int plates_size() const;
  void clear_plates();
  static const int kPlatesFieldNumber = 5;
  ::google::protobuf::int32 plates(int index) const;
  void set_plates(int index, ::google::protobuf::int32 value);
  void add_plates(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      plates() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_plates();

  // repeated float speeds = 6;
  int speeds_size() const;
  void clear_speeds();
  static const int kSpeedsFieldNumber = 6;
  float speeds(int index) const;
  void set_speeds(int index, float value);
  void add_speeds(float value);
  const ::google::protobuf::RepeatedField< float >&
      speeds() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_speeds();

  // repeated float tempurature = 8;
  int tempurature_size() const;
  void clear_tempurature();
  static const int kTempuratureFieldNumber = 8;
  float tempurature(int index) const;
  void set_tempurature(int index, float value);
  void add_tempurature(float value);
  const ::google::protobuf::RepeatedField< float >&
      tempurature() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_tempurature();

  // repeated float precipitation = 9;
  int precipitation_size() const;
  void clear_precipitation();
  static const int kPrecipitationFieldNumber = 9;
  float precipitation(int index) const;
  void set_precipitation(int index, float value);
  void add_precipitation(float value);
  const ::google::protobuf::RepeatedField< float >&
      precipitation() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_precipitation();

  // double age = 7;
  void clear_age();
  static const int kAgeFieldNumber = 7;
  double age() const;
  void set_age(double value);

  // @@protoc_insertion_point(class_scope:api.SimulationInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > elevations_;
  mutable int _elevations_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > sediment_;
  mutable int _sediment_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > plates_;
  mutable int _plates_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > speeds_;
  mutable int _speeds_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > tempurature_;
  mutable int _tempurature_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > precipitation_;
  mutable int _precipitation_cached_byte_size_;
  double age_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Basic_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GridVertex

// uint32 index = 1;
inline void GridVertex::clear_index() {
  index_ = 0u;
}
inline ::google::protobuf::uint32 GridVertex::index() const {
  // @@protoc_insertion_point(field_get:api.GridVertex.index)
  return index_;
}
inline void GridVertex::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:api.GridVertex.index)
}

// float xCoord = 2;
inline void GridVertex::clear_xcoord() {
  xcoord_ = 0;
}
inline float GridVertex::xcoord() const {
  // @@protoc_insertion_point(field_get:api.GridVertex.xCoord)
  return xcoord_;
}
inline void GridVertex::set_xcoord(float value) {
  
  xcoord_ = value;
  // @@protoc_insertion_point(field_set:api.GridVertex.xCoord)
}

// float yCoord = 3;
inline void GridVertex::clear_ycoord() {
  ycoord_ = 0;
}
inline float GridVertex::ycoord() const {
  // @@protoc_insertion_point(field_get:api.GridVertex.yCoord)
  return ycoord_;
}
inline void GridVertex::set_ycoord(float value) {
  
  ycoord_ = value;
  // @@protoc_insertion_point(field_set:api.GridVertex.yCoord)
}

// float zCoord = 4;
inline void GridVertex::clear_zcoord() {
  zcoord_ = 0;
}
inline float GridVertex::zcoord() const {
  // @@protoc_insertion_point(field_get:api.GridVertex.zCoord)
  return zcoord_;
}
inline void GridVertex::set_zcoord(float value) {
  
  zcoord_ = value;
  // @@protoc_insertion_point(field_set:api.GridVertex.zCoord)
}

// repeated uint32 neighbors = 5;
inline int GridVertex::neighbors_size() const {
  return neighbors_.size();
}
inline void GridVertex::clear_neighbors() {
  neighbors_.Clear();
}
inline ::google::protobuf::uint32 GridVertex::neighbors(int index) const {
  // @@protoc_insertion_point(field_get:api.GridVertex.neighbors)
  return neighbors_.Get(index);
}
inline void GridVertex::set_neighbors(int index, ::google::protobuf::uint32 value) {
  neighbors_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.GridVertex.neighbors)
}
inline void GridVertex::add_neighbors(::google::protobuf::uint32 value) {
  neighbors_.Add(value);
  // @@protoc_insertion_point(field_add:api.GridVertex.neighbors)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GridVertex::neighbors() const {
  // @@protoc_insertion_point(field_list:api.GridVertex.neighbors)
  return neighbors_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GridVertex::mutable_neighbors() {
  // @@protoc_insertion_point(field_mutable_list:api.GridVertex.neighbors)
  return &neighbors_;
}

// -------------------------------------------------------------------

// Grid

// uint32 totalVerts = 1;
inline void Grid::clear_totalverts() {
  totalverts_ = 0u;
}
inline ::google::protobuf::uint32 Grid::totalverts() const {
  // @@protoc_insertion_point(field_get:api.Grid.totalVerts)
  return totalverts_;
}
inline void Grid::set_totalverts(::google::protobuf::uint32 value) {
  
  totalverts_ = value;
  // @@protoc_insertion_point(field_set:api.Grid.totalVerts)
}

// repeated .api.GridVertex vertices = 3;
inline int Grid::vertices_size() const {
  return vertices_.size();
}
inline void Grid::clear_vertices() {
  vertices_.Clear();
}
inline ::api::GridVertex* Grid::mutable_vertices(int index) {
  // @@protoc_insertion_point(field_mutable:api.Grid.vertices)
  return vertices_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::api::GridVertex >*
Grid::mutable_vertices() {
  // @@protoc_insertion_point(field_mutable_list:api.Grid.vertices)
  return &vertices_;
}
inline const ::api::GridVertex& Grid::vertices(int index) const {
  // @@protoc_insertion_point(field_get:api.Grid.vertices)
  return vertices_.Get(index);
}
inline ::api::GridVertex* Grid::add_vertices() {
  // @@protoc_insertion_point(field_add:api.Grid.vertices)
  return vertices_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::api::GridVertex >&
Grid::vertices() const {
  // @@protoc_insertion_point(field_list:api.Grid.vertices)
  return vertices_;
}

// -------------------------------------------------------------------

// SimulationInfo

// repeated float elevations = 2;
inline int SimulationInfo::elevations_size() const {
  return elevations_.size();
}
inline void SimulationInfo::clear_elevations() {
  elevations_.Clear();
}
inline float SimulationInfo::elevations(int index) const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.elevations)
  return elevations_.Get(index);
}
inline void SimulationInfo::set_elevations(int index, float value) {
  elevations_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.SimulationInfo.elevations)
}
inline void SimulationInfo::add_elevations(float value) {
  elevations_.Add(value);
  // @@protoc_insertion_point(field_add:api.SimulationInfo.elevations)
}
inline const ::google::protobuf::RepeatedField< float >&
SimulationInfo::elevations() const {
  // @@protoc_insertion_point(field_list:api.SimulationInfo.elevations)
  return elevations_;
}
inline ::google::protobuf::RepeatedField< float >*
SimulationInfo::mutable_elevations() {
  // @@protoc_insertion_point(field_mutable_list:api.SimulationInfo.elevations)
  return &elevations_;
}

// repeated float sediment = 4;
inline int SimulationInfo::sediment_size() const {
  return sediment_.size();
}
inline void SimulationInfo::clear_sediment() {
  sediment_.Clear();
}
inline float SimulationInfo::sediment(int index) const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.sediment)
  return sediment_.Get(index);
}
inline void SimulationInfo::set_sediment(int index, float value) {
  sediment_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.SimulationInfo.sediment)
}
inline void SimulationInfo::add_sediment(float value) {
  sediment_.Add(value);
  // @@protoc_insertion_point(field_add:api.SimulationInfo.sediment)
}
inline const ::google::protobuf::RepeatedField< float >&
SimulationInfo::sediment() const {
  // @@protoc_insertion_point(field_list:api.SimulationInfo.sediment)
  return sediment_;
}
inline ::google::protobuf::RepeatedField< float >*
SimulationInfo::mutable_sediment() {
  // @@protoc_insertion_point(field_mutable_list:api.SimulationInfo.sediment)
  return &sediment_;
}

// repeated int32 plates = 5;
inline int SimulationInfo::plates_size() const {
  return plates_.size();
}
inline void SimulationInfo::clear_plates() {
  plates_.Clear();
}
inline ::google::protobuf::int32 SimulationInfo::plates(int index) const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.plates)
  return plates_.Get(index);
}
inline void SimulationInfo::set_plates(int index, ::google::protobuf::int32 value) {
  plates_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.SimulationInfo.plates)
}
inline void SimulationInfo::add_plates(::google::protobuf::int32 value) {
  plates_.Add(value);
  // @@protoc_insertion_point(field_add:api.SimulationInfo.plates)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SimulationInfo::plates() const {
  // @@protoc_insertion_point(field_list:api.SimulationInfo.plates)
  return plates_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SimulationInfo::mutable_plates() {
  // @@protoc_insertion_point(field_mutable_list:api.SimulationInfo.plates)
  return &plates_;
}

// repeated float speeds = 6;
inline int SimulationInfo::speeds_size() const {
  return speeds_.size();
}
inline void SimulationInfo::clear_speeds() {
  speeds_.Clear();
}
inline float SimulationInfo::speeds(int index) const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.speeds)
  return speeds_.Get(index);
}
inline void SimulationInfo::set_speeds(int index, float value) {
  speeds_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.SimulationInfo.speeds)
}
inline void SimulationInfo::add_speeds(float value) {
  speeds_.Add(value);
  // @@protoc_insertion_point(field_add:api.SimulationInfo.speeds)
}
inline const ::google::protobuf::RepeatedField< float >&
SimulationInfo::speeds() const {
  // @@protoc_insertion_point(field_list:api.SimulationInfo.speeds)
  return speeds_;
}
inline ::google::protobuf::RepeatedField< float >*
SimulationInfo::mutable_speeds() {
  // @@protoc_insertion_point(field_mutable_list:api.SimulationInfo.speeds)
  return &speeds_;
}

// double age = 7;
inline void SimulationInfo::clear_age() {
  age_ = 0;
}
inline double SimulationInfo::age() const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.age)
  return age_;
}
inline void SimulationInfo::set_age(double value) {
  
  age_ = value;
  // @@protoc_insertion_point(field_set:api.SimulationInfo.age)
}

// repeated float tempurature = 8;
inline int SimulationInfo::tempurature_size() const {
  return tempurature_.size();
}
inline void SimulationInfo::clear_tempurature() {
  tempurature_.Clear();
}
inline float SimulationInfo::tempurature(int index) const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.tempurature)
  return tempurature_.Get(index);
}
inline void SimulationInfo::set_tempurature(int index, float value) {
  tempurature_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.SimulationInfo.tempurature)
}
inline void SimulationInfo::add_tempurature(float value) {
  tempurature_.Add(value);
  // @@protoc_insertion_point(field_add:api.SimulationInfo.tempurature)
}
inline const ::google::protobuf::RepeatedField< float >&
SimulationInfo::tempurature() const {
  // @@protoc_insertion_point(field_list:api.SimulationInfo.tempurature)
  return tempurature_;
}
inline ::google::protobuf::RepeatedField< float >*
SimulationInfo::mutable_tempurature() {
  // @@protoc_insertion_point(field_mutable_list:api.SimulationInfo.tempurature)
  return &tempurature_;
}

// repeated float precipitation = 9;
inline int SimulationInfo::precipitation_size() const {
  return precipitation_.size();
}
inline void SimulationInfo::clear_precipitation() {
  precipitation_.Clear();
}
inline float SimulationInfo::precipitation(int index) const {
  // @@protoc_insertion_point(field_get:api.SimulationInfo.precipitation)
  return precipitation_.Get(index);
}
inline void SimulationInfo::set_precipitation(int index, float value) {
  precipitation_.Set(index, value);
  // @@protoc_insertion_point(field_set:api.SimulationInfo.precipitation)
}
inline void SimulationInfo::add_precipitation(float value) {
  precipitation_.Add(value);
  // @@protoc_insertion_point(field_add:api.SimulationInfo.precipitation)
}
inline const ::google::protobuf::RepeatedField< float >&
SimulationInfo::precipitation() const {
  // @@protoc_insertion_point(field_list:api.SimulationInfo.precipitation)
  return precipitation_;
}
inline ::google::protobuf::RepeatedField< float >*
SimulationInfo::mutable_precipitation() {
  // @@protoc_insertion_point(field_mutable_list:api.SimulationInfo.precipitation)
  return &precipitation_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace api

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Basic_2eproto
